import type { Metadata } from "next";
import CssBaseline from '@mui/material/CssBaseline'
import ThemeProvider from '../components/ThemeProvider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
      <CssBaseline />
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
